repository: your/repo

plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

# Custom environment variables.
# Available site-wide.
demo_var: ENV_DEMO_VAR